config/routes.rb
Packthevenue::Application.routes.draw do

  root :to => "pages#splash"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :payments, :only => [:new, :create]

  resources :activities
  
  resources :users do
  member do
    get :follow
    get :unfollow
  end
end

  devise_for :accounts, :controllers => { :omniauth_callbacks => "accounts/omniauth_callbacks", :registrations => "registrations" } do
    get "sign_up" => "registrations#new", :as => :new_account
    get "account_settings" => "registrations#edit", :as => :account_settings
    get "log_in" => "devise/sessions#new", :as => :log_in
    get "log_out" => "devise/sessions#destroy", :as => :log_out
    get "new_password" => "devise/passwords#new"
  end
  
  
  
  
  match "guest_list" => "activities#guest_list", :as => :guest_list
  
  match "close_event" => "activities#close_event", :as => :close_event
  
  
  match "make_payment" => "payments#make_payment", :as => :make_payment
  
  match "confirmation" => "payments#confirmation", :as => :confirmation
  
  
  
  match "home" => "pages#landing", :as => :landing
  
  match "how_it_works" => "pages#how_it_works", :as => :how_it_works
  
  match "jobs" => "pages#jobs", :as => :jobs
  
  match "about" => "pages#about", :as => :about
  
  match "privacy_policy" => "pages#privacy_policy", :as => :privacy_policy
  
  match "terms_and_conditions" => "pages#terms_conditions", :as => :terms_and_conditions
  
  match "pricing" => "pages#pricing", :as => :pricing
  
  match "profile" => "users#profile", :as => :profile
  
  match "splash" => "pages#splash", :as => :welcome
  
  match "not_authorized" => "pages#not_authorized", :as => :not_authorized
  
  
  
  match "search" => "application#header_search", :as => :search, :via => :get
  

 
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_filter :authenticate_account!, :only => [:dashboard]
  
  def index
@users = Account.all

respond_to do |format|
  format.html # index.html.erb
  format.xml  { render :xml => @users }
end
end
  
def follow
  user1 = Account.find(current_account)
  user2 = Account.find(params[:id])

    if user1 == user2
      flash[:error] = "You cannot follow yourself."
      redirect_to :action => :profile
    else
      user1.follow(user2)
      flash[:notice] = "You are now following #{combine_name(user2.first_name, user2.last_name)}."
      redirect_to :action => :dashboard
    end

end

def unfollow
  user1 = Account.find(current_account)
  user2 = Account.find(params[:id])
  user1.stop_following(user2)
  redirect_to :action => :dashboard
end

def profile
  @user = Account.find(current_account)
  @followers = @user.followers_count
  @activities_hosting = Activity.where(:account_id => @user)
  @activities_attending = Payment.where(:account_id => @user).select("distinct activity_id")
  @title = combine_name(@user.first_name, @user.last_name)
  
end

  def show
  @user = Account.find(params[:id])
  @title = combine_name(@user.first_name, @user.last_name)
  @followers = @user.followers_count
  @activities_hosting = Activity.where(:account_id => @user)
  @activities_attending = Payment.where(:account_id => @user)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def combine_name(first, last)
		first + " " + last
	end
end

app/views/users/index.html.erb
<div class="clear-header">
<table>
  <tr>
    <th>Name</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
  </tr>
<% end %>
</table>
</div>

app/views/users/profile.html.erb
<div class="container container-padding">
	<div class="row-fluid">
		<div class="span3 well well-small">
			
			<% if @user.photo.exists? %>
						<%= image_tag @user.photo.url(:medium) %>
					<% else %>
						<%= image_tag('profile_placeholder.png') %>
					<% end %>
			</div>
		<div class="span7">
			<h2><%= combine_name(@user.first_name, @user.last_name) %></h2>
			<h4><%= @user.company_name %></h4>
			</div>
			<div class="span2">
			<h4 class="pull-right"><%= link_to "Edit Profile", account_settings_path %></h4>
			</div>
			</div>
			
			
		<ul class="nav nav-tabs">
			<% if (@user.type_of_user != "buyer") %>
  <li class="active"><a href="#hosted_events" data-toggle="tab">Events Hosting</a></li>
   <li><a href="#attended_events" data-toggle="tab">Events Attending</a></li>
  <li><a href="#past_events" data-toggle="tab">Past Events</a></li>
  <% else %>
  <li class="active"><a href="#attended_events" data-toggle="tab">Events Attending</a></li>
  <li><a href="#past_events" data-toggle="tab">Past Events</a></li>
  <% end %>
 
</ul>


<% if (@user.type_of_user != "buyer") %>
<div class="tab-content">
  <div class="tab-pane active" id="hosted_events">
  			<div class="row">
	<% if @activities_hosting.blank? %>
    <div class="span12">
    	<h5 class="muted">You currently have no active events,
    	<%= link_to "create an event", new_activity_path %> now</h5>
    	</div>
<% else %>
	<% @activities_hosting.each do |activity| %>

	<div class="span3 profile-activity">
		<div class="row">
			<div class="span3">
				<h5 class="pull-left"><%=raw truncate(activity.name, :length => 20) %></h5>
				
				<h6><%= link_to 'View Event', activity, :class => "pull-right" %></h6>
		</div>
		</div>
		<a href="#" class="thumbnail">
      <img src="http://placehold.it/300x200" alt="">
    </a>

		</div>
		<% end %>
	<% end %>
</div>
  	</div>

  <div class="tab-pane" id="attended_events">
  			<div class="row">
	<% if @activities_attending.blank? %>
    <div class="span12">
    	<h5 class="muted">Not Attending Any Events</h5>
    	</div>
<% else %>
	<% @activities_attending.each do |payment| %>

	<div class="span3 profile-activity">
		<div class="row">
			<div class="span3">
				<h5 class="pull-left"><%=raw truncate(payment.activity.name, :length => 20) %></h5>
				
				<h6><%= link_to 'View Event', payment.activity, :class => "pull-right" %></h6>
		</div>
		</div>
		<a href="#" class="thumbnail">
      <img src="http://placehold.it/300x200" alt="">
    </a>

		</div>
		<% end %>
	<% end %>
</div>
  </div>
  <div class="tab-pane" id="past_events">
  	
  </div>
</div>
<% else %>
<div class="tab-content">
  <div class="tab-pane active" id="attended_events">
  			<div class="row">
	<% if @activities_attending.blank? %>
    <div class="span12">
    	<h5 class="muted">Not Attending Any Events</h5>
    	</div>
<% else %>
	<% @activities_attending.each do |payment| %>

	<div class="span3 profile-activity">
		<div class="row">
			<div class="span3">
				<h5 class="pull-left"><%=raw truncate(payment.activity.name, :length => 20) %></h5>
				
				<h6><%= link_to 'View Event', payment.activity, :class => "pull-right" %></h6>
		</div>
		</div>
		<a href="#" class="thumbnail">
      <img src="http://placehold.it/300x200" alt="">
    </a>

		</div>
		<% end %>
	<% end %>
</div>
  </div>
  <div class="tab-pane" id="past_events">
  	
  </div>
</div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container container-padding">
	<div class="row">
		<div class="span3 well well-large">
			</div>
			</div>
			
			
		<ul class="nav nav-tabs">
  <li class="active"><a href="#hosted_events" data-toggle="tab">Events Hosting</a></li>
  <li><a href="#attended_events" data-toggle="tab">Events Attending</a></li>
  <li><a href="#past_events" data-toggle="tab">Past Events</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="hosted_events">
  			<div class="row">
	<% if @activities_hosting.blank? %>
    <div class="span12">
    	<h5 class="muted">This User Currently Has No Active Events</h5>
    	</div>
<% else %>
	<% @activities_hosting.each do |activity| %>

	<div class="span3 profile-activity">
		<div class="row">
			<div class="span3">
				<h5 class="pull-left"><%=raw truncate(activity.name, :length => 30) %></h5>
				
				<h6><%= link_to 'View Event', activity, :class => "pull-right" %></h6>
		</div>
		</div>
		<a href="#" class="thumbnail">
      <img src="http://placehold.it/300x200" alt="">
    </a>

		</div>
		<% end %>
	<% end %>
</div>
  	</div>
  <div class="tab-pane" id="attended_events">
  			<div class="row">
	<% if @activities_attending.blank? %>
    <div class="span12">
    	<h5 class="muted">Not Attending Any Events</h5>
    	</div>
<% else %>
	<% @activities_attending.each do |payment| %>

	<div class="span3 profile-activity">
		<div class="row">
			<div class="span3">
				<h5 class="pull-left"><%=raw truncate(payment.activity.name, :length => 30) %></h5>
				
				<h6><%= link_to 'View Event', payment.activity, :class => "pull-right" %></h6>
		</div>
		</div>
		<a href="#" class="thumbnail">
      <img src="http://placehold.it/300x200" alt="">
    </a>

		</div>
		<% end %>
	<% end %>
</div>
  </div>
  <div class="tab-pane" id="past_events">
  	
  </div>
</div>
</div>