config/routes.rb
Packthevenue::Application.routes.draw do

  root :to => "pages#splash"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :payments, :only => [:new, :create]

  resources :activities
  
  resources :users do
  member do
    get :follow
    get :unfollow
  end
end

  devise_for :accounts, :controllers => { :omniauth_callbacks => "accounts/omniauth_callbacks", :registrations => "registrations" } do
    get "sign_up" => "registrations#new", :as => :new_account
    get "account_settings" => "registrations#edit", :as => :account_settings
    get "log_in" => "devise/sessions#new", :as => :log_in
    get "log_out" => "devise/sessions#destroy", :as => :log_out
    get "new_password" => "devise/passwords#new"
  end
  
  
  
  
  match "guest_list" => "activities#guest_list", :as => :guest_list
  
  match "close_event" => "activities#close_event", :as => :close_event
  
  
  match "make_payment" => "payments#make_payment", :as => :make_payment
  
  match "confirmation" => "payments#confirmation", :as => :confirmation
  
  
  
  match "home" => "pages#landing", :as => :landing
  
  match "how_it_works" => "pages#how_it_works", :as => :how_it_works
  
  match "jobs" => "pages#jobs", :as => :jobs
  
  match "about" => "pages#about", :as => :about
  
  match "privacy_policy" => "pages#privacy_policy", :as => :privacy_policy
  
  match "terms_and_conditions" => "pages#terms_conditions", :as => :terms_and_conditions
  
  match "pricing" => "pages#pricing", :as => :pricing
  
  match "profile" => "users#profile", :as => :profile
  
  match "splash" => "pages#splash", :as => :welcome
  
  match "not_authorized" => "pages#not_authorized", :as => :not_authorized
  
  
  
  match "search" => "application#header_search", :as => :search, :via => :get
  

 
  

end

app/views/pages/about.html.erb
<div class="container container-padding">
		<h4>About Us</h4>
	</div>

app/views/pages/how_it_works.html.erb
<div class="container container-padding">
		<h4>How It Works</h4>
		<div class="row">
			<div class="span6">
				Ac, a scelerisque ac. Porttitor amet ac, lundium, tristique integer porttitor pid vel! Ut. Hac, quis? 
				Tristique augue vel, sit! Sit augue. Est in dolor rhoncus in aliquet augue, auctor etiam nec integer 
				ac nunc tempor. Habitasse odio. A risus odio integer aliquam amet, parturient porttitor turpis eros! 
				Urna aenean nisi, rhoncus, nisi duis tristique rhoncus! Integer porttitor elementum sagittis, integer 
				lundium diam, integer ultricies dis? Ultricies nec? Placerat parturient rhoncus pid? Magna sit tempor 
				nunc lundium montes cras. Nisi odio pid? Cursus risus, tincidunt phasellus, sit augue phasellus aliquet 
				hac sociis nec aenean odio eu parturient et! Nec dapibus. Nunc tincidunt augue habitasse! Dignissim 
				odio, sed, facilisis et sociis! Amet sagittis in, lacus ridiculus, magnis pellentesque lorem hac, elit, 
				in turpis porta tortor mattis? Porttitor ut elit, lacus pid montes eros, porttitor mattis duis parturient, 
				mattis nunc penatibus natoque pid cum integer diam rhoncus adipiscing tempor hac nascetur, elementum duis 
				lacus, cras. Ridiculus tristique!
			</div>
			<div class="span6">
		<iframe class="pull-right" width="420" height="315" src="https://www.youtube.com/embed/XQu8TTBmGhA?rel=0" 
		frameborder="0" allowfullscreen></iframe>
		</div>
		</div>
					<h4 class="container-padding">Pricing</h4>
		<div class="row">

			</div>
	</div>

app/views/pages/jobs.html.erb
<div class="container container-padding">
		<h4>Jobs</h4>
	</div>

app/views/pages/landing.html.erb
<div id="landing">
    <div class="row">
    	<div class="container">
    	<div class="hero-unit span7 pull-right">  		
  <h1>PACK THE VENUE</h1>
  <p>Helping Venues Sell Out Events</p>
  <p>
   <%= link_to 'Learn More', how_it_works_path, :class => "btn btn-primary btn-large"  %>
  </p>
</div>
    </div>
    </div>

</div>
<div class="how-it-works container">
	<div class="row container-padding">
	<div class="span3">
	<%= image_tag('crowd_icon.png') %>
	</div>
	<div class="span8 offset1">
		<h3>NO MORE UNDER CAPACITY SHOWS </h3>
		<h4>Pack the venue enables venues bigger 
			turn outs by using a simple formula that lowers ticket prices 
			depending on the number of tickets sold.</h4>
		</div>
	</div>
	<div class="row container-padding">
	<div class="span8">
		<h3>IT'S SIMPLE </h3>
		<h4> By not charging ticket holders until
			 the end, we are able to adjust ticket prices for everyone. </h4>
		<h4> 100 people purchase tickets at $10.00, that's $1000.00 coming through the door and an under capacity show.</h4>
		<h4> 200 people purchase tickets at $8.00, thats $1600.00 coming through the door and a sold out show.</h4>
		</div>
			<div class="span3 offset1">
		 <%= image_tag('ticket_icon.png') %>
	</div>
	</div>
	<div class="row container-padding">
	<div class="span3">
      <%= image_tag('food_icon.png') %>
	</div>
	<div class="span8 offset1">
		<h3>STILL NEED CONVINCING</h3>
		<h4>According to statistics, most venues make their money from food and beverage sales. The more people in the door, the 
			more venues can sell. </h4>
		</div>
	</div>
	</div>
	
	
	<div id="register-now" class="row">

		<h1>WHAT ARE YOU WAITING FOR</h1>
		<h3><%= link_to 'Register', new_account_path  %> today and say goodbye to the days of under capacity shows.</h3>
		</div>

app/views/pages/not_authorized.html.erb
<div class="row">
	<div class="container">
<div id="not-authorized" class="alert alert-error">
  <strong>You are not authorized to view this page.</strong>
  <br><br>
You do not have permission to view this page using your current user account. 
<br><br>
Please try the following:
<br>
<ul>
	<li>If you have another user account with a higher level of permission, click your browser's Back button to try again using that account.</li>
	<li>If you believe you should be able to view this page, contact the Web site administrator.</li>
</ul>
</div>
</div>
</div>

app/views/pages/privacy_policy.html.erb
<div class="container container-padding">
		<h4>Privacy Policy</h4>
		
		<h6>INTRODUCTION</h6>
 
	<p>This Agreement contains the complete terms and conditions that apply to you in joining, 
		buying, bidding, selling and all other activities you will make in our website. By using
		 or shopping from this Web site, you agree to be bound by its terms of use and shall comply thereof. 
		 This Agreement describes and encompasses the entire agreement between us and you, and supersedes all 
		 prior or contemporaneous agreements, representations, warranties and understandings with respect to the Site, 
		 the content and computer programs provided by or through the Site, and the subject matter of this Agreement. 
		 Amendments to this agreement can be made and effected by us from time to time without specific notice to you end.
		  Agreement posted on the Site reflects the latest agreement and you should carefully review the same before you use our site. </p>
 
 
<h6>Use of the site & PROHIBITIONS</h6>
 
<p>The Site allows you to post offers, sell, advertise, bid and shop online. 
	However, you are prohibited to do the following acts, to wit: (a) use our sites, including 
	its services and or tools if you are not able to form legally binding contracts, 
	are under the age of 18, or are temporarily or indefinitely suspended from using our 
	sites, services, or tools (b) posting of an items in inappropriate category or areas on 
	our sites and services; (c) collecting information about users’ personal information; (d) 
	maneuvering the price of any item or interfere with other users' listings; (f) post false, 
	inaccurate, misleading, defamatory, or libelous content; (g) take any action that may damage the rating system.
For you to complete the sign-up process in our site, you must provide your full legal 
name, current address, a valid email address, and any other information needed in order to complete 
the signup process. You must qualify that you are 18 years or older and must be responsible for 
keeping your password secure and be responsible for all activities and contents that are uploaded 
under your account. You must not transmit any worms or viruses or any code of a destructive nature. </p>

 
<h6>Payments AND PROCESSES OF INVIOCES</h6>

 
<p> Pack The Venue has the sole discretion to provide the terms of payment. Unless otherwise agreed,
 payment must first be received by Pack The Venue prior to the latter’s acceptance of an order. 
 Unless credit term has been agreed upon, payment for the products shall be made by credit card, paypal or wire transfers.
  Invoices are due and payable within the time period noted on your invoice, measured from the date of the invoice. 
  An order may be invoice separately. Pack The Venue has all the discretion to cancel or deny orders. Pack The Venue is not responsible for 
  pricing, typographical, or other errors in any offer by Pack The Venue and reserves the right to cancel any orders arising from such errors. 
  Invoices must be paid within 15 days of the invoice date. For all but consumer purchases, Pack The Venue reserves the right to charge you
   a late penalty charge of 1% per month applied against undisputed overdue amounts or the maximum rate permitted by law whichever is less.
    Every 30 days thereafter, you will continue to be charged an additional late penalty charge. </p>

 
<h6>Refund Policy</h6>
<p>We do not have to provide a refund if you have changed your mind about a particular purchase, so please choose carefully. If the goods are
	 faulty, we will meet our obligations under the applicable laws. However, if “non-faulty” accounts are cancelled within two weeks of the first
	  payment a full refund, will be given.” </p>
 
<h6>RISK OF LOSS</h6>
<p>All items purchased from our website are made pursuant to a shipment contract. The risk of loss and title for such items 
	pass to you upon our delivery to the carrier.</p>
	
<h6>PRODUCT PRICING & DESCRIPTIONS </h6>
<p>The List Price displayed for products on our website represents the full retail price listed on the product itself, 
	suggested by the manufacturer or supplier, or estimated in accordance with standard industry practice; or the estimated 
	retail value for a comparably featured item offered elsewhere. The List Price is a comparative price estimate and may or 
	may not represent the prevailing price in every area on any particular day. For certain items that are offered as a set, 
	the List Price may represent "open-stock" prices, which means the aggregate of the manufacturer's estimated or suggested retail 
	price for each of the items included in the set. Where an item is offered for sale by one of our merchants, the List Price may
	 be provided by the merchant. In cases of mispriced in our catalogs in which the item's correct price is higher than our stated
	  price, we will, at our discretion, either contact you for instructions before shipping or cancel your order and notify you of such cancellation.
We do not warrant that product descriptions or other content of this site is accurate, complete, reliable, current, or error-free. 
If a product offered in our website is not as described, your sole remedy is to return it in unused condition. </p>
 
<h6>Editing, Deleting and Modification</h6>
 
<p>We may edit, delete or modify any of the terms and conditions contained in this Agreement, at any time and in our sole discretion, 
by posting a notice or a new agreement on our site. YOUR CONTINUED PARTICIPATION IN OUR PROGRAM, VISIT AND SHOPPING IN OUR SITE 
FOLLOWING OUR POSTING OF A CHANGE NOTICE OR NEW AGREEMENT ON OUR SITE WILL CONSTITUTE BINDING ACCEPTANCE OF THE CHANGE. </p>
 
<h6>Acknowledgment of rights</h6>
<p>You hereby acknowledge that all rights, titles and interests, including but not limited to rights covered by the Intellectual 
	Property Rights, in and to the site, and that You will not acquire any right, title, or interest in or to the Program except as expressly 
	set forth in this Agreement. You will not modify, adapt, translate, prepare derivative works from, decompile, reverse engineer, disassemble
	 or otherwise attempt to derive source code from any of our services, software, or documentation, or create or attempt to create 
	 a substitute or similar service or product through use of or access to the Program or proprietary information related thereto. </p>
 
<h6>Fraud</h6>
 
<p>FRAUDULENT ACTIVITIES are highly monitored in our site and if fraud is detected Pack The Venue shall resort al remedies available to us, 
	and you shall be responsible for all costs and legal fees arising from these fraudulent activities. </p>

 
<h6>WARRANTY DISCLAIMER AND LIMITATIONS OF LIABILITY</h6>
 
<p>We will not be liable for indirect, special, or consequential damages, or any loss of revenue, profits, or data, arising in connection with this
	 Agreement or the Program, even if we have been advised of the possibility of such damages. Further, our aggregate liability arising with
	  respect to this Agreement and the Program will not exceed USD2,000 or the total price of the subject products paid or payable to you whichever is less. </p>
<p>We make no express or implied warranties or representations with respect to the Program or any products sold and offered in our website (including, without 
limitation, warranties of fitness, merchantability, non-infringement, or any implied warranties arising out of a course of performance, dealing, or trade usage).
 In addition, we make no representation that the operation of our site will be uninterrupted or error-free, and we will not be liable for the consequences of any
  interruptions or errors. This site and its information, contents, materials, products and services are provided on an “as is” and “as available” basis. You and understand and agree that
   your use of this site is at your own risk. </p>

 

<h6>Confidentiality</h6>
<p>You agree not to disclose information you obtain from us and or from our clients, advertisers and suppliers.
	 All information submitted to by an end-user customer pursuant to a Program is proprietary information of Pack The Venue. 
	 Such customer information is confidential and may not be disclosed. Publisher agrees not to reproduce, disseminate, sell, distribute or
	  commercially exploit any such proprietary information in any manner. </p>

 
<h6>NON-WAIVER</h6>
<p>Failure of the Pack The Venue to insist upon strict performance of any of the terms, conditions and covenants hereof shall not be deemed a 
	relinquishment or waiver of any rights or remedy that the we may have, nor shall it be construed as a waiver of any subsequent breach of the terms, 
	conditions or covenants hereof, which terms, conditions and covenants shall continue to be in full force and effect.
No waiver by either party of any breach of any provision hereof shall be deemed a waiver of any subsequent or prior breach of the same or any other provision. </p>

 
<h6>MISCELLANEOUS</h6>
<p>This Agreement shall be governed by and construed in accordance with the substantive laws of Chicago, without any reference to 
	conflict-of-laws principles. Any dispute, controversy or difference which may arise between the parties out of, in relation to or 
	in connection with this Agreement is hereby irrevocably submitted to the exclusive jurisdiction of the courts of Chicago, to the
	 exclusion of any other courts without giving effect to its conflict of laws provisions or your actual state or country of residence. </p>
<p>The entire agreement between the parties with respect to the subject matter hereof is embodied on this agreement and no other agreement relative 
	hereto shall bind either party herein. Your rights of whatever nature cannot be assigned nor transferred to anybody, and any such attempt may
	 result in termination of this Agreement, without liability to us. However, we may assign this Agreement to any person at any time without notice.
In the event that any provision of these Terms and Conditions is found invalid or unenforceable pursuant to any judicial decree or decision, such
 provision shall be deemed to apply only to the maximum extent permitted by law, and the remainder of these Terms and Conditions shall remain valid
  and enforceable according to its terms. </p>
	</div>
	
	
	
	
	
	
	
	
	
	
	
	
	

app/views/pages/sign_up.html.erb
<div class="row">
	<div class="container">
		Testing registration page
		</div>
	</div>

app/views/pages/splash.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= @title.nil? ? "Pack The Venue" : "#{@title} | Pack The Venue" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'gmaps4rails' %>
  <%= csrf_meta_tags %>
</head>
<body id="splash">

	<div class="box centered">
				<br><br>
		<br><br>
		<h1>PACK THE VENUE</h1>
		<h2>Coming Soon</h2>
		<h5>Helping venues and promoters sell out events</h5>
	<!--	<a href="#videoModal" data-toggle="modal"><h3>Watch Video</h3></a> 
		<p>Enter your email address for important updates!</p>
		<div class="input-append">
<div id="mc_embed_signup">
<form action="http://packthevenue.us6.list-manage.com/subscribe/post?u=b2e80f5f8fd3aca06d9bd8383&amp;id=90f57186aa" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form">
	<div class="input-append">
			<input type="email" value="" name="EMAIL" id="mce-EMAIL" placeholder="Email Address">
            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn"></div>
	</div>
</form> -->
</div>
</div>
		</div>
		
<div id="videoModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-body">
  	<iframe width="526" height="330" src="https://www.youtube.com/embed/XQu8TTBmGhA?rel=0" 
		frameborder="1" allowfullscreen></iframe>
  </div>
    <div class="modal-footer">
    <button type="button" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

</body>
</html>


<!-- Begin MailChimp Signup Form -->



<!--End mc_embed_signup-->

app/views/pages/terms_conditions.html.erb
<div class="container container-padding">
		<h4>Terms and Conditions</h4>
		
		<h6>INTRODUCTION</h6>
 
	<p>This Agreement contains the complete terms and conditions that apply to you in joining, 
		buying, bidding, selling and all other activities you will make in our website. By using
		 or shopping from this Web site, you agree to be bound by its terms of use and shall comply thereof. 
		 This Agreement describes and encompasses the entire agreement between us and you, and supersedes all 
		 prior or contemporaneous agreements, representations, warranties and understandings with respect to the Site, 
		 the content and computer programs provided by or through the Site, and the subject matter of this Agreement. 
		 Amendments to this agreement can be made and effected by us from time to time without specific notice to you end.
		  Agreement posted on the Site reflects the latest agreement and you should carefully review the same before you use our site. </p>
 
 
<h6>Use of the site & PROHIBITIONS</h6>
 
<p>The Site allows you to post offers, sell, advertise, bid and shop online. 
	However, you are prohibited to do the following acts, to wit: (a) use our sites, including 
	its services and or tools if you are not able to form legally binding contracts, 
	are under the age of 18, or are temporarily or indefinitely suspended from using our 
	sites, services, or tools (b) posting of an items in inappropriate category or areas on 
	our sites and services; (c) collecting information about users’ personal information; (d) 
	maneuvering the price of any item or interfere with other users' listings; (f) post false, 
	inaccurate, misleading, defamatory, or libelous content; (g) take any action that may damage the rating system.
For you to complete the sign-up process in our site, you must provide your full legal 
name, current address, a valid email address, and any other information needed in order to complete 
the signup process. You must qualify that you are 18 years or older and must be responsible for 
keeping your password secure and be responsible for all activities and contents that are uploaded 
under your account. You must not transmit any worms or viruses or any code of a destructive nature. </p>

 
<h6>Payments AND PROCESSES OF INVIOCES</h6>

 
<p> Pack The Venue has the sole discretion to provide the terms of payment. Unless otherwise agreed,
 payment must first be received by Pack The Venue prior to the latter’s acceptance of an order. 
 Unless credit term has been agreed upon, payment for the products shall be made by credit card, paypal or wire transfers.
  Invoices are due and payable within the time period noted on your invoice, measured from the date of the invoice. 
  An order may be invoice separately. Pack The Venue has all the discretion to cancel or deny orders. Pack The Venue is not responsible for 
  pricing, typographical, or other errors in any offer by Pack The Venue and reserves the right to cancel any orders arising from such errors. 
  Invoices must be paid within 15 days of the invoice date. For all but consumer purchases, Pack The Venue reserves the right to charge you
   a late penalty charge of 1% per month applied against undisputed overdue amounts or the maximum rate permitted by law whichever is less.
    Every 30 days thereafter, you will continue to be charged an additional late penalty charge. </p>

 
<h6>Refund Policy</h6>
<p>We do not have to provide a refund if you have changed your mind about a particular purchase, so please choose carefully. If the goods are
	 faulty, we will meet our obligations under the applicable laws. However, if “non-faulty” accounts are cancelled within two weeks of the first
	  payment a full refund, will be given.” </p>
 
<h6>RISK OF LOSS</h6>
<p>All items purchased from our website are made pursuant to a shipment contract. The risk of loss and title for such items 
	pass to you upon our delivery to the carrier.</p>
	
<h6>PRODUCT PRICING & DESCRIPTIONS </h6>
<p>The List Price displayed for products on our website represents the full retail price listed on the product itself, 
	suggested by the manufacturer or supplier, or estimated in accordance with standard industry practice; or the estimated 
	retail value for a comparably featured item offered elsewhere. The List Price is a comparative price estimate and may or 
	may not represent the prevailing price in every area on any particular day. For certain items that are offered as a set, 
	the List Price may represent "open-stock" prices, which means the aggregate of the manufacturer's estimated or suggested retail 
	price for each of the items included in the set. Where an item is offered for sale by one of our merchants, the List Price may
	 be provided by the merchant. In cases of mispriced in our catalogs in which the item's correct price is higher than our stated
	  price, we will, at our discretion, either contact you for instructions before shipping or cancel your order and notify you of such cancellation.
We do not warrant that product descriptions or other content of this site is accurate, complete, reliable, current, or error-free. 
If a product offered in our website is not as described, your sole remedy is to return it in unused condition. </p>
 
<h6>Editing, Deleting and Modification</h6>
 
<p>We may edit, delete or modify any of the terms and conditions contained in this Agreement, at any time and in our sole discretion, 
by posting a notice or a new agreement on our site. YOUR CONTINUED PARTICIPATION IN OUR PROGRAM, VISIT AND SHOPPING IN OUR SITE 
FOLLOWING OUR POSTING OF A CHANGE NOTICE OR NEW AGREEMENT ON OUR SITE WILL CONSTITUTE BINDING ACCEPTANCE OF THE CHANGE. </p>
 
<h6>Acknowledgment of rights</h6>
<p>You hereby acknowledge that all rights, titles and interests, including but not limited to rights covered by the Intellectual 
	Property Rights, in and to the site, and that You will not acquire any right, title, or interest in or to the Program except as expressly 
	set forth in this Agreement. You will not modify, adapt, translate, prepare derivative works from, decompile, reverse engineer, disassemble
	 or otherwise attempt to derive source code from any of our services, software, or documentation, or create or attempt to create 
	 a substitute or similar service or product through use of or access to the Program or proprietary information related thereto. </p>
 
<h6>Fraud</h6>
 
<p>FRAUDULENT ACTIVITIES are highly monitored in our site and if fraud is detected Pack The Venue shall resort al remedies available to us, 
	and you shall be responsible for all costs and legal fees arising from these fraudulent activities. </p>

 
<h6>WARRANTY DISCLAIMER AND LIMITATIONS OF LIABILITY</h6>
 
<p>We will not be liable for indirect, special, or consequential damages, or any loss of revenue, profits, or data, arising in connection with this
	 Agreement or the Program, even if we have been advised of the possibility of such damages. Further, our aggregate liability arising with
	  respect to this Agreement and the Program will not exceed USD2,000 or the total price of the subject products paid or payable to you whichever is less. </p>
<p>We make no express or implied warranties or representations with respect to the Program or any products sold and offered in our website (including, without 
limitation, warranties of fitness, merchantability, non-infringement, or any implied warranties arising out of a course of performance, dealing, or trade usage).
 In addition, we make no representation that the operation of our site will be uninterrupted or error-free, and we will not be liable for the consequences of any
  interruptions or errors. This site and its information, contents, materials, products and services are provided on an “as is” and “as available” basis. You and understand and agree that
   your use of this site is at your own risk. </p>

 

<h6>Confidentiality</h6>
<p>You agree not to disclose information you obtain from us and or from our clients, advertisers and suppliers.
	 All information submitted to by an end-user customer pursuant to a Program is proprietary information of Pack The Venue. 
	 Such customer information is confidential and may not be disclosed. Publisher agrees not to reproduce, disseminate, sell, distribute or
	  commercially exploit any such proprietary information in any manner. </p>

 
<h6>NON-WAIVER</h6>
<p>Failure of the Pack The Venue to insist upon strict performance of any of the terms, conditions and covenants hereof shall not be deemed a 
	relinquishment or waiver of any rights or remedy that the we may have, nor shall it be construed as a waiver of any subsequent breach of the terms, 
	conditions or covenants hereof, which terms, conditions and covenants shall continue to be in full force and effect.
No waiver by either party of any breach of any provision hereof shall be deemed a waiver of any subsequent or prior breach of the same or any other provision. </p>

 
<h6>MISCELLANEOUS</h6>
<p>This Agreement shall be governed by and construed in accordance with the substantive laws of Chicago, without any reference to 
	conflict-of-laws principles. Any dispute, controversy or difference which may arise between the parties out of, in relation to or 
	in connection with this Agreement is hereby irrevocably submitted to the exclusive jurisdiction of the courts of Chicago, to the
	 exclusion of any other courts without giving effect to its conflict of laws provisions or your actual state or country of residence. </p>
<p>The entire agreement between the parties with respect to the subject matter hereof is embodied on this agreement and no other agreement relative 
	hereto shall bind either party herein. Your rights of whatever nature cannot be assigned nor transferred to anybody, and any such attempt may
	 result in termination of this Agreement, without liability to us. However, we may assign this Agreement to any person at any time without notice.
In the event that any provision of these Terms and Conditions is found invalid or unenforceable pursuant to any judicial decree or decision, such
 provision shall be deemed to apply only to the maximum extent permitted by law, and the remainder of these Terms and Conditions shall remain valid
  and enforceable according to its terms. </p>
	</div>
	
	
	
	
	
	
	
	
	
	
	
	
	