config/routes.rb
Packthevenue::Application.routes.draw do

  root :to => "pages#splash"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :payments, :only => [:new, :create]

  resources :activities
  
  resources :users do
  member do
    get :follow
    get :unfollow
  end
end

  devise_for :accounts, :controllers => { :omniauth_callbacks => "accounts/omniauth_callbacks", :registrations => "registrations" } do
    get "sign_up" => "registrations#new", :as => :new_account
    get "account_settings" => "registrations#edit", :as => :account_settings
    get "log_in" => "devise/sessions#new", :as => :log_in
    get "log_out" => "devise/sessions#destroy", :as => :log_out
    get "new_password" => "devise/passwords#new"
  end
  
  
  
  
  match "guest_list" => "activities#guest_list", :as => :guest_list
  
  match "close_event" => "activities#close_event", :as => :close_event
  
  
  match "make_payment" => "payments#make_payment", :as => :make_payment
  
  match "confirmation" => "payments#confirmation", :as => :confirmation
  
  
  
  match "home" => "pages#landing", :as => :landing
  
  match "how_it_works" => "pages#how_it_works", :as => :how_it_works
  
  match "jobs" => "pages#jobs", :as => :jobs
  
  match "about" => "pages#about", :as => :about
  
  match "privacy_policy" => "pages#privacy_policy", :as => :privacy_policy
  
  match "terms_and_conditions" => "pages#terms_conditions", :as => :terms_and_conditions
  
  match "pricing" => "pages#pricing", :as => :pricing
  
  match "profile" => "users#profile", :as => :profile
  
  match "splash" => "pages#splash", :as => :welcome
  
  match "not_authorized" => "pages#not_authorized", :as => :not_authorized
  
  
  
  match "search" => "application#header_search", :as => :search, :via => :get
  

 
  

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :status, :quantity, :uri
  validates_presence_of :status, :quantity, :uri
  
    belongs_to :account
    belongs_to :activity
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include PaymentsHelper
  
	before_filter :authenticate_account!, :except => [:make_payment, :confirmation]
	
	def make_payment
    session["ticket_quantity"] = params[:ticket_quantity]
    session["activity_id"] = params[:activity_id]
    redirect_to confirmation_path
  end
	
	def confirmation
		@account = Account.new
		@payment = Payment.new
		@fees = ((session["current_price"].to_i * 0.029) + 0.30) * session["ticket_quantity"].to_i
		@subtotal = session["current_price"] * session["ticket_quantity"].to_i
		@total = @fees + @subtotal
	end
	
	def create 
	  @payment = Payment.new(params[:payment])
	  @account = Account.find(current_account.id)
    @payment.account_id = current_account.id
    @payment.activity_id = session["activity_id"]
    @payment.quantity = session["ticket_quantity"]
    @payment.status = "Card Verified"
    @payment.uri = params[:payment][:uri]
    
    card = Balanced::Card.find(params[:payment][:uri])
    if card.is_valid 
      account = Balanced::Account.find("/v1/marketplaces/TEST-MP6AYyZ4i81jgO8P66ljOWH8/accounts/#{@account.balanced_account_id}")
      account.add_card(params[:payment][:uri])
      if @payment.save 
        redirect_to profile_path
        EventMailer.event_tickets_email(@payment).deliver
      else
        redirect_to :controller => 'activity', :action => 'show(@payment.activity_id)'
      end
    else
       redirect_to :controller => 'activity', :action => 'show(@payment.activity_id)'
    end
	end
end

app/helpers/payments_helper.rb
module PaymentsHelper
	def activitySuccess(activity)
		p = Payment.find(:all, :conditions => {:activity_id => activity.id})
		count = 0
		p.each do |payment|
			count = count + payment.tickets.size
		end
		activity.min_signups - count
	end
	
	def ticketsBought(activity, accountId)
		p = Payment.find(:all, :conditions => {:activity_id => activity.id, :account_id => accountId})
		count = 1
		p.each do |payment|
			payment.tickets.each do |t|
				count = count + 1
			end
		end
		count - 1
	end
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.number_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/confirmation.html.erb
<div class="container container-padding">
	<div id="confirmation" class="page-wrapper">
	      	 
	      	 <h4>Invoice</h4>
<% activity = Activity.find(session["activity_id"]) %>
				<table class="table table-striped">
  <thead>
    <tr>
      <th>Event Name</th>
      <th>Venue</th>
      <th>Seat</th>
      <th>Current Ticket Price</th>
    </tr>
  </thead>
  <tbody>
  	<% count = 1 %>
  	<% while count <= session["ticket_quantity"].to_i %>
	    	<tr>
	    		<td><%= activity.name %></td>
	    		<td></td>
	      	<td>General Admission</td>
	      	<td><%= number_to_currency(session["current_price"]) %></td>
	    	</tr>
	 <% count = count + 1 %>
	 <% end %>
  </tbody>
</table>
<div class="row-fluid">
	<div class="span12">
		<span class="pull-right"><strong>Subtotal:</strong> <%= number_to_currency(@subtotal) %> </span> 
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<span class="pull-right"><strong>Ticket Fees:</strong> <%= number_to_currency(@fees) %> </span> 
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<span class="pull-right"><strong>Tentative Total:</strong> <%= number_to_currency(@total) %> </span> 
	</div>
</div>



 <%= form_for @payment do |f|  %>
 

  <fieldset>
    <legend>Enter Payment Information</legend>
    <label>Card Holder Name</label>
    <input type="text" class="span5" placeholder="John Doe" name="name">
    <label>Card Number</label>
    <input type="text" class="span5" placeholder="1234 5678 9876 5432" name="card_number">
    <label>Security Code</label>
    <input type="text" class="span1" placeholder="888" name="security_code">
    <label>Expiration Date</label>
   	<input type="text" class="span1" name="expiration_month" placeholder="02"> /
        <input type="text" class="span1" name="expiration_year" placeholder="2015">
    <%= f.submit 'Place Order', :class => 'btn btn-primary pull-right', :id => "submit-button" %>
  </fieldset>
  
  <%= f.hidden_field :uri %>
  
 <% end %>
 
  <div class="well well-small">
 	NOTE: Your tickets will be emailed to you. Please print them off and bring them with you.
 </div>
 </div>
</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.code %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @payment.code %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>