config/routes.rb
Packthevenue::Application.routes.draw do

  root :to => "pages#splash"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :payments, :only => [:new, :create]

  resources :activities
  
  resources :users do
  member do
    get :follow
    get :unfollow
  end
end

  devise_for :accounts, :controllers => { :omniauth_callbacks => "accounts/omniauth_callbacks", :registrations => "registrations" } do
    get "sign_up" => "registrations#new", :as => :new_account
    get "account_settings" => "registrations#edit", :as => :account_settings
    get "log_in" => "devise/sessions#new", :as => :log_in
    get "log_out" => "devise/sessions#destroy", :as => :log_out
    get "new_password" => "devise/passwords#new"
  end
  
  
  
  
  match "guest_list" => "activities#guest_list", :as => :guest_list
  
  match "close_event" => "activities#close_event", :as => :close_event
  
  
  match "make_payment" => "payments#make_payment", :as => :make_payment
  
  match "confirmation" => "payments#confirmation", :as => :confirmation
  
  
  
  match "home" => "pages#landing", :as => :landing
  
  match "how_it_works" => "pages#how_it_works", :as => :how_it_works
  
  match "jobs" => "pages#jobs", :as => :jobs
  
  match "about" => "pages#about", :as => :about
  
  match "privacy_policy" => "pages#privacy_policy", :as => :privacy_policy
  
  match "terms_and_conditions" => "pages#terms_conditions", :as => :terms_and_conditions
  
  match "pricing" => "pages#pricing", :as => :pricing
  
  match "profile" => "users#profile", :as => :profile
  
  match "splash" => "pages#splash", :as => :welcome
  
  match "not_authorized" => "pages#not_authorized", :as => :not_authorized
  
  
  
  match "search" => "application#header_search", :as => :search, :via => :get
  

 
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :address, :city, :description, :end, :latitude, :longitude, :name, :photo, :category,
  :start, :state, :zip, :ticket_types_attributes, :location_description, :min_capacity, :reduced_ticket, 
  :starting_ticket, :include_fee, :max_capacity, :final_price, :status
  belongs_to :account
  has_many :payments, :dependent => :destroy
  
  validates_presence_of :name, :description, :start, :end, :address, :city, :zip
 
  acts_as_followable
  
  has_many :ticket_types, :dependent => :destroy
  
  accepts_nested_attributes_for :ticket_types, :allow_destroy => true

	acts_as_gmappable
	
	def gmaps4rails_address
	  "#{self.address}, #{self.city}, #{self.state}" 
	end
	
  has_attached_file :photo, :styles => { :large => "670x392", :medium => "362x400", :thumb => "100x100>" }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  
  before_filter :authenticate_account!, :except => [:show]
  
  load_and_authorize_resource
  skip_authorize_resource :only => :show

  def index
    @activities = Activity.all
  end

  def guest_list
    @activity = Activity.find(params[:id])
    @payments = Payment.find(:all, :conditions => {:activity_id => @activity.id})
  end

  def show
    @activity = Activity.find(params[:id])
    @map = @activity.to_gmaps4rails
    @tickets_remaining = @activity.max_capacity - view_context.ticketsSold(@activity)
    @guest_list = Payment.where(:activity_id => @activity.id).select("distinct account_id")
   
    if view_context.ticketsSold(@activity) > @activity.min_capacity
      @current_price = currentTicketPrice(@activity)
       session["current_price"] = @current_price
      @saving_price = @activity.starting_ticket - @current_price
    else
      @current_price = @activity.starting_ticket
      session["current_price"] = @current_price
      @saving_price = 0
    end
  end

  def new
    @activity = Activity.new
    @activity.ticket_types.build    
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = Activity.new(params[:activity])
    @activity.account_id = current_account.id
    @activity.status = "created"
    if @activity.save 
      redirect_to @activity
    else
      render :action => :new
    end
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update_attributes(params[:activity])
      redirect_to @activity
    else
      render :action => :new
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_path
  end
  
  def close_event
    @activity = Activity.find(params[:id])
    @activity.status = "Processing"
    if view_context.ticketsSold(@activity) > @activity.min_capacity
      @activity.final_price = currentTicketPrice(@activity).to_i * 100
    else
      @activity.final_price = (@activity.starting_ticket).to_i * 100
    end
    if @activity.save 
      redirect_to @activity
    else
      redirect_to @activity
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end

  def categories
    [
      ['Concert', 'Concert'],
      ['Theater', 'Theater'],
      ['Other', 'Other']
    ]
  end
end

app/views/activities/_form.html.erb
<div id="create-event" class="container">
		  <% if @activity.errors.any? %>
    <div class="alert alert-error">
      <%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
	<div class="span12">
		<legend>General Information</legend>
		</div>
	<div class="span8">
		<%= nested_form_for @activity, :html => { :multipart => true } do |f| %>
	
	<div class="controls controls-row">
			<%= f.text_field :name, :placeholder => 'Event Name', :class=> "span5" %>
			<%= f.select :category, categories, {:include_blank => 'Select Category...'}, {:class => "span3"} %>
			</div>	
		<div class="controls-row">
			<%= f.text_area :description, :id => "create_textarea", :placeholder => 'Event Description', :class=> "span8", :rows => "20" %>
			</div>
		<div class="controls-row">
			<%= f.text_field :start, :placeholder => "Event Date", 'data-behaviour' => 'datepicker', :class => "span4" %>
			<%= f.text_field :end, :class => "span4 offset1", :placeholder => "Event Time", :id => 'activity-time', 'data-format' => "hh:mm A" %>
			
		</div>
			<div class="controls-row">
				<%= f.file_field :photo %>
			</div>
	</div>
		<div class="span3 offset1">
		<div class="well">
			<p>Enter a name, category, description, date, and time for your event. </p>
			<p> It is also recommended that you upload a picture
				to represent your event ie. Flyer, company logo etc...</p>
			</div>
			</div>
			</div>
			<div class="row">
			<div class="span12">
		<legend>Location</legend>
		</div>
	<div class="span9">
			
			<%= f.text_field :address, :placeholder => 'Street', :class => "span8" %>
			<div class="controls-row">
			<%= f.text_field :city, :placeholder => 'City', :class => "span3" %>
			<%= f.select :state, us_states, {:include_blank => 'Select State...'}, {:class => "span3"} %>
			<%= f.text_field :zip, :placeholder => 'Zip Code', :class => "span2" %>
			</div>
			<div class="controls-row">
			<%= f.text_area :location_description, :placeholder => 'Additional Location Information', :class=> "span8", :rows => "5" %>
			</div>
			</div>
			<div class="span3">
		<div class="well">
			<p>Enter the events address here. You can also provide additional information
				if neccessary to help insure that your guests have no problems finding your event.</p>
			</div>
			</div>
			</div>
			<div class="row">
			<div class="span12">
		<legend>Ticket Information</legend>
		</div>
	<div class="span9">
		<h5>When you venue has hit max capacity, how many people can it hold?</h5>

			<%= f.text_field :max_capacity, :placeholder=>"Max Capacity", :class => "span2" %>
			<h5>How much will tickets cost at full capacity?</h5>
			<%= f.text_field :reduced_ticket, :placeholder=>"Discounted Ticket Price", :class => "span3" %>
			<h5>How many people before price reduction starts?</h5>
			<%= f.text_field :min_capacity, :placeholder=>"Min Capacity", :class => "span2" %>
			<h5>How much will tickets cost before price reduction starts?</h5>
			<%= f.text_field :starting_ticket, :placeholder=>"Starting Ticket Price", :class => "span3" %>


	</div>
		<div class="span3">
		<div class="well">
			Directions
			</div>
			</div>
			</div>
	

	<div class="row">
		<div class="span9">
    <%= f.submit :class => 'btn btn-primary pull-right' %>
</div>
</div>
	</div>
<% end %>

app/views/activities/edit.html.erb
<%= render :partial => "../partials/admin_panel"%>

<div class="container container-padding">
<%= render 'form' %>
</div>

app/views/activities/guest_list.html.erb
<%= render :partial => "../partials/admin_panel"%>

<div class="container container-padding">
	
	<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
<% @payments.each do |payments| %>
<tr>
	<td><%= combine_name(payments.account.first_name, payments.account.last_name) %></td>
	<td class="text-center"><%= payments.quantity %></td>
	<td><%= payments.status %></td>
</tr>
<% end %>
  </tbody>
</table>
</div>

app/views/activities/index.html.erb
<div id="find-activity">
	<div class="row search">
		test
	</div>
	<div class="row">
		<div class="side-bar">
			Test
			</div>

		<div class="map-container">
			

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start</th>
    <th>End</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.name %></td>
    <td><%= activity.description %></td>
    <td><%= activity.start %></td>
    <td><%= activity.end %></td>
    <td><%= activity.address %></td>
    <td><%= activity.city %></td>
    <td><%= activity.state %></td>
    <td><%= activity.zip %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>
</div>

app/views/activities/new.html.erb
<%= render 'form' %>

app/views/activities/show.html.erb
<%= render :partial => "../partials/admin_panel"%>

<div id="show-event" class="container container-padding">
	<div class="page-wrapper">

	<div class="row-fluid">
		<div class="span4">
			<% if @activity.photo.exists? %>
						<%= image_tag @activity.photo.url(:medium) %>
					<% else %>
						<%= image_tag('profile_placeholder.png') %>
					<% end %>
    <div class="row-fluid">
    	<div class="span12">
    <h4>Event Location</h4>
    <address>
  		<strong>Venue Name</strong><br>
  			<%= @activity.address %><br>
  			<%= @activity.city %>, <%= @activity.state %> <%= @activity.zip %><br>
  			P: (555) 555-5555
	</address>    
    </div>
    </div>
    <div class="row-fluid">
    	<div class="span12">
    <h4>Event Map</h4>
			
    </div>
    </div>
    <div class="row-fluid">
    	<div class="span12">
    <h4>Event Guest List</h4>
    <p class="muted"><%= ticketsSold(@activity) %> people attending</p>
 		<% @guest_list.each do |guest| %>
 		<% if guest.account.photo.exists? %>
 			<%= image_tag guest.account.photo.url(:thumb) %>
 			<% end %>
		<% end %>
    </div>
    </div>
		</div>
		<div class="offset1 span7">
			<h2><%= @activity.name %></h2>
				<div id="show-event-prices" class="row-fluid">
				<div class="span4 well well-small">
					<h3 class="text-center"><%= @tickets_remaining %></h3>
					Tickets Remaining
					</div>
					<div class="span4 well well-small">
					<h3><%= number_to_currency(@current_price) %></h3>
					Current Ticket Price
					</div>
					<div class="span4 well well-small">
					<h3><%= number_to_currency(@saving_price) %></h3>
					Total Savings
					</div>
			<div class="row">
				<div class="span12">
			<p class="muted">Note: Event must sell <%= @activity.min_capacity %> tickets before discount begins</p>
			</div>
			</div>
			</div>
			
			<div class="row-fluid">
				<div class="span12">
			<h4>Event Description</h4>
			<p><%= raw @activity.description %></p>
			</div>
			</div>
			
			<div class="row-fluid">
				<div class="span12">
			<h4>Event Tickets</h4>
				<table class="table">
  <thead>
    <tr>
      <th style="width: 90%">Seat</th>
      <th style="width: 10%">Quantity</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>General Admission</td>
      <td>
      	<%= form_tag make_payment_path do %>
		<%= select_tag :ticket_quantity, options_for_select(["1", "2", "3", "4"]), :class => 'span12' %>
      </td>
    </tr>
  </tbody>
</table>

  		<%= hidden_field_tag :activity_id, @activity.id %>
    	<%= submit_tag "Check Out", :class=>"btn btn-primary pull-right" %>
	<% end %>
		</div>
		
</div>
</div>
</div>
</div>
</div>